spring.application.name=vidgrab
server.port=8080

# MySQL (apna username/password yahan badlein)
spring.datasource.url=jdbc:mysql://localhost:3306/vidgrab?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=akash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# yt-dlp ka path (PATH me hai to sirf yt-dlp likhein)
app.ytdlp.path=C:/Users/akash/OneDrive/Documents/youtub/yt-dlp.exe
# ffmpeg install hai to true karein (1080p+ aur best quality ke liye)
app.ffmpeg.enabled=true
app.timeout.seconds=180
